image: 'neubi4/flutter-build-image:latest'

stages:
  - build

build:
  stage: build
  script:
    - echo $key | base64 -d > /root/key.jks
    - echo $key_properties | base64 -d >  android/key.properties
    - ls -la
    - ls -la android
    - cat android/key.properties
    - ls -la /root/key.jks
    - flutter build apk --split-per-abi --flavor default
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/*.apk
    expire_in: 1 day
