---
name: Build App

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: build app
        run: flutter build apk --split-per-abi --no-shrink --flavor stage
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kikke-android
          path: build/app/outputs/flutter-apk/*.apk
  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - name: build app
        run: flutter build windows
      - name: copy windows dlls
        run: |
          copy C:\Windows\System32\msvcp140.dll build\windows\runner\Release\msvcp140.dll
          copy C:\Windows\System32\vcruntime140.dll build\windows\runner\Release\vcruntime140.dll
          copy C:\Windows\System32\vcruntime140_1.dll build\windows\runner\Release\vcruntime140_1.dll
      - name: pack zip
        run: |
          powershell Compress-Archive -Path build\windows\runner\Release\* -DestinationPath kikke-windows-zip.zip
      - name: create package
        run: flutter pub run msix:create
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kikke-windows
          path: build/windows/runner/Release/*.msix
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kikke-windows-zip
          path: kikke-windows-zip.zip
