name: Build
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
  pull_request:

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: build app
        run: flutter build apk --split-per-abi --no-shrink --flavor stage
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kikke-android
          path: build/app/outputs/flutter-apk/*.apk
